# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patronazna_sluzba_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
