# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patronazna_sluzba_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delovni_nalog',
            name='cas_obiskov_tip',
            field=models.CharField(blank=True, choices=[('Interval', 'Casovni interval med zaporednima obiskoma v dnevih'), ('Obdobje', 'Stevilo dni, v katerih mora biti obisk opravljen')], max_length=10),
        ),
        migrations.AlterField(
            model_name='delovni_nalog',
            name='obveznost_obiska',
            field=models.CharField(blank=True, choices=[('Obvezen', 'Prvi obisk se mora opraviti na tocen dan'), ('Okviren', 'Prvi obisk se lahko opravi v vec dnevih')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='spol',
            field=models.CharField(choices=[('M', 'Moski'), ('Z', 'Zenska')], max_length=1),
        ),
        migrations.AlterField(
            model_name='vrsta_obiska',
            name='ime',
            field=models.CharField(choices=[('I', 'Aplikacija inekcij'), ('K', 'Odvzem krvi'), ('Z', 'Kontrola zdravstvenega stanja'), ('N', 'Obisk nosecnice'), ('O', 'Obisk otrocnice'), ('R', 'Obisk novorojencka'), ('S', 'Obisk starostnika')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vrsta_obiska',
            name='tip',
            field=models.CharField(choices=[('P', 'Preventivni obisk'), ('K', 'Kurativni obisk')], max_length=10, null=True),
        ),
    ]
