# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 05:28
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patronazna_sluzba_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delovni_nalog',
            name='cas_obiskov_tip',
            field=models.CharField(blank=True, choices=[('Interval', 'Casovni interval med zaporednima obiskoma v dnevih'), ('Obdobje', 'Stevilo dni, v katerih mora biti obisk opravljen')], max_length=10),
        ),
        migrations.AlterField(
            model_name='nadomescanje',
            name='datum_konec',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 13, 7, 28, 37, 678769)),
        ),
        migrations.AlterField(
            model_name='nadomescanje',
            name='datum_zacetek',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 12, 7, 28, 37, 678769)),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='spol',
            field=models.CharField(choices=[('M', 'Moski'), ('Z', 'Zenska')], max_length=1),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='st_kartice',
            field=models.CharField(default=-1, max_length=12, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Dovoljena zgolj stevilska vrednost.'), django.core.validators.MinLengthValidator(12, 'Stevilka kartica je dolzine 12 znakov.'), django.core.validators.MaxLengthValidator(12, 'Stevilka kartica je dolzine 12 znakov.')]),
        ),
        migrations.AlterField(
            model_name='plan',
            name='datum',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 13, 7, 28, 37, 663142)),
        ),
        migrations.AlterField(
            model_name='vrsta_obiska',
            name='ime',
            field=models.CharField(choices=[('I', 'Aplikacija inekcij'), ('K', 'Odvzem krvi'), ('Z', 'Kontrola zdravstvenega stanja'), ('N', 'Obisk nosecnice'), ('O', 'Obisk otrocnice in novorojencka'), ('S', 'Obisk starostnika')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vrsta_obiska',
            name='tip',
            field=models.CharField(choices=[('P', 'Preventivni obisk'), ('K', 'Kurativni obisk')], max_length=10, null=True),
        ),
    ]
