# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patronazna_sluzba_app', '0002_auto_20170426_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='delovni_nalog',
            name='obveznost_obiska',
            field=models.CharField(blank=True, choices=[('Obvezen', 'Prvi obisk se mora opraviti na tocen dan'), ('Okviren', 'Prvi obisk se lahko opravi v vec dnevih')], max_length=10),
        ),
        migrations.AlterField(
            model_name='delovni_nalog',
            name='zdravnik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patronazna_sluzba_app.Zdravnik'),
        ),
    ]
