# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 03:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patronazna_sluzba_app', '0002_auto_20170518_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nadomescanje',
            name='datum_konec',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 19, 5, 28, 48, 78113)),
        ),
        migrations.AlterField(
            model_name='nadomescanje',
            name='datum_zacetek',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 18, 5, 28, 48, 78089)),
        ),
        migrations.AlterField(
            model_name='plan',
            name='datum',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 19, 5, 28, 48, 76567)),
        ),
    ]
