# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 19:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patronazna_sluzba_app', '0002_auto_20170413_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='uporabniski_profil',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
