# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 00:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patronazna_sluzba_app', '0002_auto_20170531_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nadomescanje',
            name='datum_konec',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 2, 0, 10, 41, 520280)),
        ),
        migrations.AlterField(
            model_name='nadomescanje',
            name='datum_zacetek',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 1, 0, 10, 41, 520257)),
        ),
        migrations.AlterField(
            model_name='plan',
            name='datum',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 2, 0, 10, 41, 518633)),
        ),
        migrations.AlterUniqueTogether(
            name='nadomescanje',
            unique_together=set([('sestra', 'datum_zacetek', 'datum_konec', 'nadomestna_sestra')]),
        ),
        migrations.AlterUniqueTogether(
            name='porocilo_o_obisku',
            unique_together=set([('obisk', 'polje', 'pacient')]),
        ),
    ]
