# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patronazna_sluzba_app', '0002_blacklist_ip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blacklist_ip',
        ),
        migrations.AddField(
            model_name='pacient',
            name='aktiviran',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
