# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 11:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patronazna_sluzba_app', '0002_auto_20170506_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='datum',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 7, 13, 41, 1, 152539)),
        ),
        migrations.AlterField(
            model_name='vrsta_obiska',
            name='ime',
            field=models.CharField(choices=[('I', 'Aplikacija inekcij'), ('K', 'Odvzem krvi'), ('Z', 'Kontrola zdravstvenega stanja'), ('N', 'Obisk nosecnice'), ('O', 'Obisk otrocnice in novorojencka'), ('S', 'Obisk starostnika')], max_length=10),
        ),
    ]
