# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patronazna_sluzba_app', '0002_auto_20170413_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patronazna_sestra',
            name='okolis',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='patronazna_sluzba_app.Okolis'),
        ),
        migrations.AlterField(
            model_name='patronazna_sestra',
            name='sifra_izvajalca_ZS',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patronazna_sluzba_app.Izvajalec_ZS'),
        ),
        migrations.AlterField(
            model_name='sodelavec_zd',
            name='sifra_izvajalca_ZS',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patronazna_sluzba_app.Izvajalec_ZS'),
        ),
        migrations.AlterField(
            model_name='vodja_ps',
            name='sifra_izvajalca_ZS',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patronazna_sluzba_app.Izvajalec_ZS'),
        ),
        migrations.AlterField(
            model_name='zdravnik',
            name='sifra_izvajalca_ZS',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patronazna_sluzba_app.Izvajalec_ZS'),
        ),
    ]
