# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patronazna_sluzba_app', '0002_auto_20170428_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delovni_nalog',
            name='bolezen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patronazna_sluzba_app.Bolezen'),
        ),
    ]
