# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patronazna_sluzba_app', '0002_auto_20170413_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacient',
            name='aktiviran',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
