# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patronazna_sluzba_app', '0003_auto_20170428_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='obisk',
            name='p_sestra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patronazna_sluzba_app.Patronazna_sestra'),
        ),
    ]
