# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 07:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patronazna_sluzba_app', '0003_auto_20170503_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='obisk',
            name='p_sestra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patronazna_sluzba_app.Patronazna_sestra'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='datum',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 4, 9, 46, 34, 715867)),
        ),
    ]
