# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 16:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patronazna_sluzba_app', '0003_auto_20170601_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nadomescanje',
            name='datum_konec',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 2, 16, 51, 29, 621870)),
        ),
        migrations.AlterField(
            model_name='nadomescanje',
            name='datum_zacetek',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 1, 16, 51, 29, 621848)),
        ),
        migrations.AlterField(
            model_name='plan',
            name='datum',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 2, 16, 51, 29, 620202)),
        ),
    ]
