# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 11:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patronazna_sluzba_app', '0003_auto_20170506_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='datum',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 7, 13, 43, 21, 159137)),
        ),
    ]
