# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 00:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patronazna_sluzba_app', '0003_auto_20170529_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='polje_v_porocilu',
            name='obvezno',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='nadomescanje',
            name='datum_konec',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 31, 0, 30, 58, 408848)),
        ),
        migrations.AlterField(
            model_name='nadomescanje',
            name='datum_zacetek',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 30, 0, 30, 58, 408823)),
        ),
        migrations.AlterField(
            model_name='plan',
            name='datum',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 31, 0, 30, 58, 407138)),
        ),
    ]
