# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-02 02:41
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patronazna_sluzba_app', '0004_auto_20170601_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='obisk',
            name='n_sestra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nadomestna_sestra', to='patronazna_sluzba_app.Patronazna_sestra'),
        ),
        migrations.AlterField(
            model_name='delovni_nalog',
            name='cas_obiskov_tip',
            field=models.CharField(blank=True, choices=[('Interval', 'Casovni interval med zaporednima obiskoma v dnevih'), ('Obdobje', 'Stevilo dni, v katerih mora biti obisk opravljen')], max_length=10),
        ),
        migrations.AlterField(
            model_name='nadomescanje',
            name='datum_konec',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 3, 2, 41, 56, 652125)),
        ),
        migrations.AlterField(
            model_name='nadomescanje',
            name='datum_zacetek',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 2, 2, 41, 56, 652125)),
        ),
        migrations.AlterField(
            model_name='obisk',
            name='p_sestra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sestra', to='patronazna_sluzba_app.Patronazna_sestra'),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='spol',
            field=models.CharField(choices=[('M', 'Moski'), ('Z', 'Zenska')], max_length=1),
        ),
        migrations.AlterField(
            model_name='pacient',
            name='st_kartice',
            field=models.CharField(default=-1, max_length=12, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Dovoljena zgolj stevilska vrednost.'), django.core.validators.MinLengthValidator(12, 'Stevilka kartica je dolzine 12 znakov.'), django.core.validators.MaxLengthValidator(12, 'Stevilka kartica je dolzine 12 znakov.')]),
        ),
        migrations.AlterField(
            model_name='plan',
            name='datum',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 3, 2, 41, 56, 650123)),
        ),
        migrations.AlterField(
            model_name='vrsta_obiska',
            name='ime',
            field=models.CharField(choices=[('I', 'Aplikacija inekcij'), ('K', 'Odvzem krvi'), ('Z', 'Kontrola zdravstvenega stanja'), ('N', 'Obisk nosecnice'), ('O', 'Obisk otrocnice in novorojencka'), ('S', 'Obisk starostnika')], max_length=10),
        ),
        migrations.AlterField(
            model_name='vrsta_obiska',
            name='tip',
            field=models.CharField(choices=[('P', 'Preventivni obisk'), ('K', 'Kurativni obisk')], max_length=10, null=True),
        ),
    ]
