# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patronazna_sluzba_app', '0004_obisk_p_sestra'),
    ]

    operations = [
        migrations.AddField(
            model_name='obisk',
            name='obvezen_obisk',
            field=models.BooleanField(default=0),
        ),
    ]
