# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 16:41
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patronazna_sluzba_app', '0004_auto_20170503_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='st_kartice',
            field=models.CharField(default=-1, max_length=12, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Dovoljena zgolj stevilska vrednost.'), django.core.validators.MinLengthValidator(12, 'Stevilka kartica je dolzine 12 znakov.'), django.core.validators.MaxLengthValidator(12, 'Stevilka kartica je dolzine 12 znakov.')]),
        ),
        migrations.AlterField(
            model_name='plan',
            name='datum',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 4, 18, 41, 49, 729439)),
        ),
    ]
