# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 17:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patronazna_sluzba_app', '0005_auto_20170503_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='datum',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 4, 19, 1, 0, 631400)),
        ),
    ]
