# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 18:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patronazna_sluzba_app', '0006_auto_20170503_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='datum',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 4, 20, 6, 54, 149655)),
        ),
    ]
